name: PR Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  comprehensive-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.6'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Create Firebase options stub for CI
      run: |
        if [ ! -f "lib/firebase_options.dart" ]; then
          cp lib/firebase_options_stub.dart lib/firebase_options.dart
        fi
    
    - name: Create google-services.json for CI
      run: |
        if [ ! -f "android/app/google-services.json" ]; then
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > android/app/google-services.json
        fi
    
    - name: Analyze code
      run: flutter analyze --no-fatal-warnings
    
    - name: Run all tests
      run: flutter test --timeout=120s
    
    - name: Build debug APK (validation)
      run: flutter build apk --debug