name: Push Tests

on:
  push:
    branches-ignore: [ main ]
  workflow_dispatch:

jobs:
  quick-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.6'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Create Firebase options stub for CI
      run: |
        if [ ! -f "lib/firebase_options.dart" ]; then
          cp lib/firebase_options_stub.dart lib/firebase_options.dart
        fi
    
    - name: Analyze code
      run: flutter analyze
    
    - name: Run unit tests
      run: flutter test --timeout=120s